apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  labels:
    app: kyverno
    managed-by: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gmedeirosnet/CI.CD
    targetRevision: feature--Kyverno
    path: k8s/kyverno/policies
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health assessment
  ignoreDifferences:
  - group: kyverno.io
    kind: ClusterPolicy
    jsonPointers:
    - /status
