apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
type: Opaque
data:
  # Password is base64 encoded - default: "postgres123"
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
